trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'
- task: CopyFiles@2
  displayName: 'Copy and Rename to ROOT.war'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/target/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
    flattenFolders: true

- script: |
    cd $(build.artifactstagingdirectory)
    # This finds whatever war was copied and renames it to ROOT.war
    mv *.war ROOT.war
  displayName: 'Rename for Tomcat'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'FirstWARFile'